## RMS Feb 2017
## Compile C code for Hermann code prep

BIN  = bin
CFLAGS = -Wall -g -O3 -lm
CC = gcc
OBJS = dispersion_db_to_hermann_input.c
 
all:
	$(CC) $(OBJS) $(CFLAGS) -o $(BIN)/dispersion_db_to_hermann.exe

clean:
	rm -f $(BIN)/*


