#RMS Feb 2017

BIN = bin
CFLAGS = -Wall -g
HEADERFLAGS = -I/data/dna/rmartin/Ambient_noise/CODES/include/
LIBFLAGS = -lm 

CC = gcc

all:
	$(CC) stack_rp_with_io.c $(CFLAGS) $(HEADERFLAGS) $(LIBFLAGS) $(LIBDIRFLAGS) -o $(BIN)/Stack_RP_with_IO.exe
