#RMS Feb 2017 

BIN = bin
CFLAGS = -Wall -g -O3
HEADERFLAGS = -I../../include
LIBFLAGS = -lm
CC = gcc

all: 
	$(CC) cut_to_sym_component.c $(CFLAGS) $(HEADERFLAGS) $(LIBFLAGS) -o $(BIN)/Cut_To_Sym_Comps.exe
